version: '3.4'

networks:
  default:
    driver: bridge

services:
  ondemeutimejoga:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "8000:443"
    volumes:
      - ..:/workspace:cached
      - /certs:/etc/ssl/certs
    environment:
      - SSL_CERTIFICATE=/etc/ssl/certs/fullchain.pem
      - SSL_CERTIFICATE_KEY=/etc/ssl/certs/privkey.pem
    networks:
      - default