version: '3.4'

networks:
  default:
    driver: bridge

services:
  ondemeutimejoga:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./certs:/etc/ssl/certs
    environment:
      - SSL_CERTIFICATE=/etc/ssl/certs/fullchain.pem
      - SSL_CERTIFICATE_KEY=/etc/ssl/certs/privkey.pem
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    depends_on:
      - ondemeutimejoga
    networks:
      - default